query BookById($book_id: ID!) {
  book(book_id: $book_id) {
    book_id
    author
    category
    cover
    name
    price
    rating
    recommendationsFromAuthor {
      book_id
      name
      cover
    }
    recommendationsFromCustomers {
      book_id
      name
      cover
    }
  }
  recommendationsFromPurchases(email: "demi@bookstore.com") {
    book_id
    name
    cover
  }
}