
query SearchBooks($query: String) {
  search(query: $query) {
    results {
      book_id
      author
      category
      cover
      name
      price
      rating
    }
    price_ranges {
      key
      doc_count
    }
    categories {
      key
      doc_count
    }
    rating_ranges {
      key
      doc_count
    }
  }
}