apiVersion: v1
kind: Service
metadata:
  name: passwordless-service
spec:
  type: ClusterIP
  selector:
    app: passwordless-app
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: passwordless-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passwordless-app
  template:
    metadata:
      labels:
        app: passwordless-app
    spec:
      containers:
        - name: passwordless-container
          image: kpatel20538/bookstore-app:passwordless
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 256Mi
              cpu: 200m
            requests:
              memory: 256Mi
              cpu: 200m
          env:
            - name: STMP_HOST
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: stmp_host
            - name: STMP_PORT
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: stmp_port
            - name: STMP_USER
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: stmp_user
            - name: STMP_PASS
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: stmp_pass
            - name: STMP_FROM
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: stmp_from
            - name: ELASTIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: elastic_api_key
            - name: JWT_OTP_ISS
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: jwt_otp_iss
            - name: JWT_OTP_AUD
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: jwt_otp_aud
            - name: JWT_OTP_ALG
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: jwt_otp_alg
            - name: JWT_OTP_EXP
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: jwt_otp_exp
            - name: JWT_OTP_KEY
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: jwt_otp_key
            - name: JWT_ACCESS_ISS
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: jwt_access_iss
            - name: JWT_ACCESS_AUD
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: jwt_access_aud
            - name: JWT_ACCESS_ALG
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: jwt_access_alg
            - name: JWT_ACCESS_EXP
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: jwt_access_exp
            - name: JWT_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: jwt_access_key
            - name: SUCCESS_REDIRECT
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: success_redirect
            - name: FAILED_REDIRECT
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: failed_redirect
            - name: HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: passwordless-secret
                  key: hostname
