antiAffinity: "soft"

esJavaOpts: "-Xmx128m -Xms128m"

replicas: 1
minimumMasterNodes: 1

resources:
  requests:
    cpu: "100m"
    memory: "512M"
  limits:
    cpu: "1000m"
    memory: "512M"

volumeClaimTemplate:
  resources:
    requests:
      storage: 100M

sysctlInitContainer:
  enabled: false

ingress:
  enabled: true
  annotations:
    dev.okteto.com/generate-host: "true"