antiAffinity: "soft"

esJavaOpts: "-Xmx128m -Xms128m"

replicas: 1
minimumMasterNodes: 1

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Mi

volumeClaimTemplate:
  resources:
    requests:
      storage: 100Mi

sysctlInitContainer:
  enabled: false

ingress:
  enabled: true
  annotations:
    dev.okteto.com/generate-host: "true"